[package]
name = "system_information"
version = "0.1.0"
authors = ["Jack Sauriol <saurioljohn@gmail.com>"]

[dependencies]
regex = "0.2.6"

[target.'cfg(windows)'.dependencies]
winutil = "0.1.1"
winapi = "0.3.4"
